production:
  facebook_api: "188745724592284"
  facebook_secret: "f73e33e90f9af793b3da3680988d7a5a"
  yahoo_api: "xxxxxxxxxxxxx"
  yahoo_secret: "xxxxxxxxxxxxx"
  twitter_api: "nviNsQlu0KcIkXuKkW1DnA"
  twitter_secret: "pJnVRTQHPJ5RsRnFPlqifyFftEUa8S9iA5nuJBVaAE"
  google_api: "1017355479913-digo5hpqhp2o3rqaht77udt9mjpmnt2p.apps.googleusercontent.com"
  google_secret: "NWNS1ZIn98_Acv4aui4Xy6ft"
  linkedin_api: "r30hprac8c6s"
  linkedin_secret: "ylNpvGjuzXTypsn7"

development:
  facebook_api: "188745724592284"
  facebook_secret: "f73e33e90f9af793b3da3680988d7a5a"
  yahoo_api: "xxxxxxxxxxxxx"
  yahoo_secret: "xxxxxxxxxxxxx"
  twitter_api: "nviNsQlu0KcIkXuKkW1DnA"
  twitter_secret: "pJnVRTQHPJ5RsRnFPlqifyFftEUa8S9iA5nuJBVaAE"
  google_api: "1017355479913-digo5hpqhp2o3rqaht77udt9mjpmnt2p.apps.googleusercontent.com"
  google_secret: "NWNS1ZIn98_Acv4aui4Xy6ft"
  linkedin_api: "r30hprac8c6s"
  linkedin_secret: "ylNpvGjuzXTypsn7"

test:
  facebook_api: "xxxxxxxxxxxxx"
  facebook_secret: "xxxxxxxxxxxxx"
  yahoo_api: "xxxxxxxxxxxxx"
  yahoo_secret: "xxxxxxxxxxxxx"
  twitter_api: "xxxxxxxxxxxxx"
  twitter_secret: "xxxxxxxxxxxxx"
  google_api: "xxxxxxxxxxxxx"
  google_secret: "xxxxxxxxxxxxx"
  bitly_user: "xxxxxxxxxxxxx"
  bitly_api: "xxxxxxxxxxxxx"
